name: 1xbetwebsite.in

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SECRET_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: rm -rf .git .github
      - run: rm .gitignore
      # Deploy
      - run: cd ./ && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@165.232.179.213:/home/1xbetwebsite_in/web/1xbetwebsite.in/public_html/wp-content/plugins/MatchCenter/countries_flags/
      - run: cd ./ && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@165.232.179.213:/home/1xbetwebsite_in/web/staging.1xbetwebsite.in/public_html/wp-content/plugins/MatchCenter/countries_flags/
